#This file tells Ansible that the commands must be run in the local host
all:
  hosts:
    localhost:
      vars:
        ansible_connection: local
        password: 123456
        discord_client_secret: ic-hrzagt5
